let g:NERDTreeWinSize = 50
let g:NERDTreeChDirMode = 2
let g:NERDTreeMinimalMenu = 1
let g:NERDTreeCascadeSingleChildDir = 0
let g:NERDTreeDirArrowExpandable = '+'
let g:NERDTreeDirArrowCollapsible = '-'
let g:NERDTreeStatusline = 1
" let g:NERDTreeWinPos = 0
let g:NERDTreeQuitOnOpen = 1
